const dndData = [

    { name: "Bardic Inspiration", race: "General", class: "Bard", type: "Bonus Action", dice: "1d6", desc: "Bir arkadaşına moral verirsin, sonraki zarına 1d6 ekler." },
    { name: "Song of Rest", race: "General", class: "Bard", type: "Pasif", dice: "1d6 Can", desc: "Dinlenme sırasında şarkılarınla grubun daha fazla can yenilemesini sağlarsın." },
    { name: "Jack of All Trades", race: "General", class: "Bard", type: "Pasif", dice: "+Yarım Bonus", desc: "Bilmediğin her yetenek zarına (Gizlilik, Atletizm vb.) yarım bonus eklersin." },
    { name: "Expertise", race: "General", class: "Bard", type: "Pasif", dice: "x2 Uzmanlık", desc: "Seçtiğin iki yetenekte (Örn: İkna ve Yalan) uzmanlık bonusunu ikiye katlarsın." },
    { name: "Countercharm", race: "General", class: "Bard", type: "Action", dice: "Avantaj", desc: "Müzik yaparak grubun korkutulmasını veya büyülenmesini engellersin." },
    { name: "Magical Secrets", race: "General", class: "Bard", type: "Pasif", dice: "-", desc: "Başka sınıfların (Büyücü, Rahip gibi) büyülerini çalarsın." },
    { name: "Font of Inspiration", race: "General", class: "Bard", type: "Pasif", dice: "-", desc: "Kısa dinlenmelerde bile Bardic Inspiration haklarını geri kazanırsın." },
    { name: "Superior Inspiration", race: "General", class: "Bard", type: "Pasif", dice: "-", desc: "Savaşa girdiğinde hiç moral verme hakkın yoksa otomatik 1 hak kazanırsın." },
    { name: "Words of Terror", race: "General", class: "Bard", type: "Action", dice: "Korku", desc: "Konuşmanla birinin içine korku salar ve onu ürkütürsün." },
    { name: "Vicious Mockery", race: "General", class: "Bard", type: "Action", dice: "1d4 Psişik", desc: "Düşmana o kadar ağır hakaret edersin ki canı acır ve ıskalar." },

    { name: "Arcane Recovery", race: "General", class: "Wizard", type: "Pasif", dice: "Büyü Slotu", desc: "Kısa bir mola verip ders çalışarak kullandığın büyü slotlarını geri alırsın." },
    { name: "Spellbook", race: "General", class: "Wizard", type: "Pasif", dice: "-", desc: "Dünyadaki tüm büyüleri kitabına yazabilir ve devasa bir büyü listesine sahip olabilirsin." },
    { name: "Arcane Tradition", race: "General", class: "Wizard", type: "Pasif", dice: "-", desc: "İllüzyon, Ateş veya Necromancy gibi bir büyü okulunda uzmanlaşırsın." },
    { name: "Sculpt Spells", race: "General", class: "Wizard", type: "Pasif", dice: "-", desc: "Alan büyüleri yaparken arkadaşlarına zarar vermemek için büyünün şeklini bükersin." },
    { name: "Portent (Kehanet)", race: "General", class: "Wizard", type: "Pasif", dice: "Zarı Sakla", desc: "Güne iki zar atarak başlarsın ve gün içinde herhangi bir zarı bu sayılarla değiştirebilirsin." },
    { name: "Minor Conjuration", race: "General", class: "Wizard", type: "Action", dice: "-", desc: "Havadan küçük, cansız bir eşya (Anahtar, kupa vb.) yaratırsın." },
    { name: "Hypnotic Gaze", race: "General", class: "Wizard", type: "Action", dice: "Wis Sav.", desc: "Birinin gözlerinin içine bakarak onu büyüleyip hareketsiz bırakırsın." },
    { name: "Arcane Deflection", race: "General", class: "Wizard", type: "Reaction", dice: "+2 AC", desc: "Sana saldırıldığında anlık bir büyü kalkanı oluşturursun." },
    { name: "Signature Spells", race: "General", class: "Wizard", type: "Pasif", dice: "-", desc: "En sevdiğin iki büyüyü artık büyü slotu harcamadan yapabilirsin." },
    { name: "Master Spell", race: "General", class: "Wizard", type: "Pasif", dice: "-", desc: "En güçlü büyülerinden birini her an yapmaya hazır tutarsın." },

    { name: "Divine Domain", race: "General", class: "Cleric", type: "Pasif", dice: "-", desc: "Tanrından gelen gücün kaynağını (Işık, Savaş, Yaşam) belirlersin." },
    { name: "Channel Divinity", race: "General", class: "Cleric", type: "Action", dice: "Mucize", desc: "Tanrının gücünü doğrudan dünyaya indirerek mucizeler yaratırsın." },
    { name: "Turn Undead", race: "General", class: "Cleric", type: "Action", dice: "Kaçış", desc: "Etrafındaki tüm zombileri ve hayaletleri kutsal ışığınla kaçırırsın." },
    { name: "Destroy Undead", race: "General", class: "Cleric", type: "Action", dice: "Anlık Ölüm", desc: "Güçsüz hortlakları sadece varlığınla küle çevirirsin." },
    { name: "Divine Intervention", race: "General", class: "Cleric", type: "Action", dice: "d100", desc: "Tanrını doğrudan yardıma çağırırsın. Zar tutarsa Tanrı savaşa müdahale eder!" },
    { name: "Disciple of Life", race: "General", class: "Cleric", type: "Pasif", dice: "+2 Can", desc: "Yaptığın her iyileştirme büyüsü ekstra can puanı kazandırır." },
    { name: "Preserve Life", race: "General", class: "Cleric", type: "Action", dice: "Grup İyileşme", desc: "Etrafındaki tüm arkadaşlarına aynı anda kutsal enerjiyle can verirsin." },
    { name: "Warding Flare", race: "General", class: "Cleric", type: "Reaction", dice: "Dezavantaj", desc: "Sana saldıranın gözüne ışık tutarak ıskalamasını sağlarsın." },
    { name: "Wrath of the Storm", race: "General", class: "Cleric", type: "Reaction", dice: "2d8 Yıldırım", desc: "Sana vurana şimşekle karşılık verirsin." },
    { name: "Eyes of Night", race: "General", class: "Cleric", type: "Pasif", dice: "Sınırsız Görüş", desc: "Karanlıkta bile bir gündüz gibi net görebilirsin." },

    { name: "Fighting Style", race: "General", class: "Fighter", type: "Pasif", dice: "-", desc: "Okçuluk, savunma veya iki silah kullanma gibi bir tarzda uzmanlaşırsın." },
    { name: "Second Wind", race: "General", class: "Fighter", type: "Bonus Action", dice: "1d10+Sev", desc: "Savaşta bir kez derin nefes alıp canını tazelersin." },
    { name: "Action Surge", race: "General", class: "Fighter", type: "Action", dice: "+1 Ek Tur", desc: "Aynı turda bir kez daha ana hamle yapabilirsin. (Çok güçlü!)" },
    { name: "Extra Attack", race: "General", class: "Fighter", type: "Action", dice: "+1 Saldırı", desc: "Aksiyon harcadığında bir değil, iki (veya daha fazla) kez vurursun." },
    { name: "Indomitable", race: "General", class: "Fighter", type: "Reaction", dice: "Zar Tekrarı", desc: "Başarısız olduğun bir savunma zarını iradenle tekrar atarsın." },
    { name: "Martial Archetype", race: "General", class: "Fighter", type: "Pasif", dice: "-", desc: "Şövalye, Samuray veya Büyülü Savaşçı gibi bir yol seçersin." },
    { name: "Combat Superiority", race: "General", class: "Fighter", type: "Pasif", dice: "d8 Zar", desc: "Özel savaş manevraları yaparak düşmanı yere serer veya silahını düşürürsün." },
    { name: "Student of War", race: "General", class: "Fighter", type: "Pasif", dice: "-", desc: "Zırh ve silah yapımı konusunda teknik bilgi kazanırsın." },
    { name: "Know Your Enemy", race: "General", class: "Fighter", type: "Pasif", dice: "-", desc: "Birine 1 dakika bakarak onun senden güçlü mü yoksa zayıf mı olduğunu anlarsın." },
    { name: "Survivor", race: "General", class: "Fighter", type: "Pasif", dice: "Otomatik Can", desc: "Canın çok azaldığında her tur başında otomatik olarak canın dolar." },

    { name: "Sneak Attack", race: "General", class: "Rogue", type: "Pasif", dice: "Ekstra d6", desc: "Düşman gafil avlandığında ona devasa hasar verirsin." },
    { name: "Cunning Action", race: "General", class: "Rogue", type: "Bonus Action", dice: "-", desc: "Her tur bedavadan Kaçma, Gizlenme veya Depar atabilirsin." },
    { name: "Thieves' Cant", race: "General", class: "Rogue", type: "Pasif", dice: "Gizli Dil", desc: "Hırsızların kullandığı gizli sembolleri ve konuşmaları anlarsın." },
    { name: "Uncanny Dodge", race: "General", class: "Rogue", type: "Reaction", dice: "Yarı Hasar", desc: "Sana vurulduğunda vücudunu bükerek hasarı yarıya indirirsin." },
    { name: "Evasion", race: "General", class: "Rogue", type: "Pasif", dice: "0 Hasar", desc: "Patlamalardan (Ateş topu vb.) çevikliğinle hiç hasar almadan kurtulursun." },
    { name: "Reliable Talent", race: "General", class: "Rogue", type: "Pasif", dice: "Min 10", desc: "Bildiğin yeteneklerde (Gizlilik vb.) asla 10'un altında zar atmazsın." },
    { name: "Blindsense", race: "General", class: "Rogue", type: "Pasif", dice: "3 Metre", desc: "Görmesen bile etrafındaki canlıların yerini nefeslerinden anlarsın." },
    { name: "Slippery Mind", race: "General", class: "Rogue", type: "Pasif", dice: "-", desc: "Zihnini kontrol etmeye çalışan büyülere karşı çelik gibi iraden vardır." },
    { name: "Stroke of Luck", race: "General", class: "Rogue", type: "Pasif", dice: "Otomatik Başarı", desc: "Iskaladığın bir saldırıyı veya başarısız olduğun zarı otomatik başarıya çevirirsin." },
    { name: "Fast Hands", race: "General", class: "Rogue", type: "Bonus Action", dice: "-", desc: "Savaşın ortasında birinin cebinden anahtar çalabilir veya kilit açabilirsin." },

    { name: "Divine Smite", race: "General", class: "Paladin", type: "Action", dice: "2d8+ Hasar", desc: "Silahını kutsal enerjiyle doldurup düşmanı yakarsın." },
    { name: "Lay on Hands", race: "General", class: "Paladin", type: "Action", dice: "Can Havuzu", desc: "Dokunarak arkadaşını iyileştirir veya zehrini temizlersin." },
    { name: "Divine Sense", race: "General", class: "Paladin", type: "Action", dice: "-", desc: "Etrafındaki kötü varlıkları (Şeytan, Vampir vb.) hissedersin." },
    { name: "Aura of Protection", race: "General", class: "Paladin", type: "Pasif", dice: "+Bonus", desc: "Senin yanında duran herkes büyüye karşı daha dirençli olur." },
    { name: "Sacred Oath", race: "General", class: "Paladin", type: "Pasif", dice: "-", desc: "Tanrına veya idealine ettiğin yemin (İntikam, Sadakat vb.) sana güç verir." },
    { name: "Divine Health", race: "General", class: "Paladin", type: "Pasif", dice: "-", desc: "Vücudun o kadar kutsaldır ki asla hastalanmazsın." },
    { name: "Aura of Courage", race: "General", class: "Paladin", type: "Pasif", dice: "-", desc: "Senin yanındaki hiç kimse korku etkisine giremez." },
    { name: "Improved Divine Smite", race: "General", class: "Paladin", type: "Pasif", dice: "+1d8", desc: "Her vuruşun artık otomatik olarak kutsal ışık hasarı verir." },
    { name: "Cleansing Touch", race: "General", class: "Paladin", type: "Action", dice: "-", desc: "Birinin üzerindeki kötü büyüyü sadece dokunarak silersin." },
    { name: "Divine Champion", race: "General", class: "Paladin", type: "Action", dice: "Dönüşüm", desc: "Kısa süreliğine bir yarı-tanrıya dönüşüp yenilmez olursun." },

    { name: "Rage (Öfke)", race: "General", class: "Barbarian", type: "Bonus Action", dice: "+Hasar", desc: "Öfkeye kapılır, daha çok vurur ve fiziksel hasarlara direnirsin." },
    { name: "Unarmored Defense", race: "General", class: "Barbarian", type: "Pasif", dice: "10+DEX+CON", desc: "Zırh giymediğinde bile tenin çelik kadar serttir." },
    { name: "Reckless Attack", race: "General", class: "Barbarian", type: "Action", dice: "Avantaj", desc: "Savunmanı bırakıp saldırırsın. Vurma şansın artar ama sana da kolay vururlar." },
    { name: "Danger Sense", race: "General", class: "Barbarian", type: "Pasif", dice: "Avantaj", desc: "Tuzakları ve tehlikeleri önceden sezersin." },
    { name: "Feral Instinct", race: "General", class: "Barbarian", type: "Pasif", dice: "İnisiyatif", desc: "Asla gafil avlanmazsın ve savaşa herkesten önce başlarsın." },
    { name: "Brutal Critical", race: "General", class: "Barbarian", type: "Pasif", dice: "Ekstra Zar", desc: "Kritik vurduğunda kemik kıran devasa hasarlar verirsin." },
    { name: "Relentless Rage", race: "General", class: "Barbarian", type: "Pasif", dice: "Direnç", desc: "Canın 0'a düşse bile öfkenle ayakta kalmaya devam edersin." },
    { name: "Persistent Rage", race: "General", class: "Barbarian", type: "Pasif", dice: "-", desc: "Öfken artık sadece sen istediğinde biter, yorularak bitmez." },
    { name: "Indomitable Might", race: "General", class: "Barbarian", type: "Pasif", dice: "Min Stat", desc: "Güç gerektiren hiçbir işte başarısız olamazsın." },
    { name: "Primal Champion", race: "General", class: "Barbarian", type: "Pasif", dice: "+4 Güç/Day", desc: "Vücudun tanrısal sınırlara ulaşır, Güç ve Dayanıklılığın aşırı artar." },

    { name: "Wild Shape", race: "General", class: "Druid", type: "Action", dice: "Hayvana Dönüş", desc: "Ayı, kurt, kuş veya örümcek gibi hayvanlara dönüşebilirsin." },
    { name: "Druidic", race: "General", class: "Druid", type: "Pasif", dice: "Gizli Dil", desc: "Doğanın ve bitkilerin gizli dilini bilirsin." },
    { name: "Natural Recovery", race: "General", class: "Druid", type: "Pasif", dice: "Büyü Slotu", desc: "Toprakla temas ederek büyü gücünü geri kazanırsın." },
    { name: "Circle Forms", race: "General", class: "Druid", type: "Pasif", dice: "Güçlü Hayvan", desc: "Çok daha tehlikeli ve büyük canavarlara (Mamut vb.) dönüşebilirsin." },
    { name: "Combat Wild Shape", race: "General", class: "Druid", type: "Bonus Action", dice: "-", desc: "Savaşın ortasında anlık olarak hayvana dönüşebilir ve can yenileyebilirsin." },
    { name: "Elemental Wild Shape", race: "General", class: "Druid", type: "Action", dice: "Elementel", desc: "Hava, Ateş, Su veya Toprak elementallerine dönüşebilirsin." },
    { name: "Archdruid", race: "General", class: "Druid", type: "Pasif", dice: "Sınırsız", desc: "İstediğin kadar hayvana dönüşebilirsin, sınırın yoktur." },
    { name: "Speech of the Woods", race: "General", class: "Druid", type: "Pasif", dice: "-", desc: "Tüm hayvanlarla konuşabilir ve onlara emir verebilirsin." },
    { name: "Timeless Body", race: "General", class: "Druid", type: "Pasif", dice: "-", desc: "Doğa seni korur, normalden 10 kat daha yavaş yaşlanırsın." },
    { name: "Hidden Step", race: "General", class: "Druid", type: "Bonus Action", dice: "Görünmezlik", desc: "Doğa ana seni gizler, bir süreliğine görünmez olursun." },

    { name: "Otherworldly Patron", race: "General", class: "Warlock", type: "Pasif", dice: "-", desc: "Gücünü aldığın karanlık varlık (Şeytan, Kadim Varlık vb.)." },
    { name: "Pact Magic", race: "General", class: "Warlock", type: "Pasif", dice: "Max Büyü", desc: "Büyülerin her zaman en güçlü seviyede atılır." },
    { name: "Eldritch Invocations", race: "General", class: "Warlock", type: "Pasif", dice: "Modifikasyon", desc: "Büyülerine karanlık özellikler eklersin (Örn: Duvar arkasını görme)." },
    { name: "Eldritch Blast", race: "General", class: "Warlock", type: "Action", dice: "1d10 Enerji", desc: "Parmak uçlarından saf enerji fırlatırsın. Warlockların vazgeçilmezidir." },
    { name: "Pact Boon", race: "General", class: "Warlock", type: "Pasif", dice: "-", desc: "Efendinden bir hediye alırsın (Büyülü kitap, kılıç veya yardımcı yaratık)." },
    { name: "Mystic Arcanum", race: "General", class: "Warlock", type: "Action", dice: "Üst Seviye", desc: "Efendinden aldığın en güçlü gizli büyüleri yaparsın." },
    { name: "Eldritch Master", race: "General", class: "Warlock", type: "Action", dice: "Slot Yenileme", desc: "Efendine dua ederek tüm büyü gücünü 1 dakikada geri alırsın." },
    { name: "Devil's Sight", race: "General", class: "Warlock", type: "Pasif", dice: "36 Metre", desc: "Büyülü karanlıkta bile (Normalde kimse göremez) net görürsün." },
    { name: "Agonizing Blast", race: "General", class: "Warlock", type: "Pasif", dice: "+CHA Hasar", desc: "Enerji patlamana karizma bonusunu ekleyerek hasarı artırırsın." },
    { name: "Mask of Many Faces", race: "General", class: "Warlock", type: "Pasif", dice: "Disguise Self", desc: "Sınırsızca kılık değiştirebilirsin." },

    { name: "Favored Enemy", race: "General", class: "Ranger", type: "Pasif", dice: "-", desc: "Belirli bir tür düşmanı (Örn: Ejderhalar) izleme ve öldürmede uzmansın." },
    { name: "Natural Explorer", race: "General", class: "Ranger", type: "Pasif", dice: "-", desc: "Vahşi doğada (Orman, Çöl vb.) asla kaybolmaz ve grubu hızlandırırsın." },
    { name: "Primeval Awareness", race: "General", class: "Ranger", type: "Action", dice: "-", desc: "Odaklanarak etrafındaki canavarların varlığını hissedersin." },
    { name: "Land's Stride", race: "General", class: "Ranger", type: "Pasif", dice: "-", desc: "Dikenli yollar veya büyülü bitkiler seni yavaşlatamaz." },
    { name: "Hide in Plain Sight", race: "General", class: "Ranger", type: "Action", dice: "+10 Gizlilik", desc: "Doğal malzemelerle kamuflaj yapıp heykel gibi beklersen kimse seni göremez." },
    { name: "Vanish", race: "General", class: "Ranger", type: "Bonus Action", dice: "Gizlen", desc: "Savaşın ortasında bir anda izini kaybettirebilirsin." },
    { name: "Feral Senses", race: "General", class: "Ranger", type: "Pasif", dice: "-", desc: "Görmediğin düşmanların yerini sezebilir ve onları ıskalamazsın." },
    { name: "Foe Slayer", race: "General", class: "Ranger", type: "Pasif", dice: "+Bonus", desc: "Bilgeliğini kullanarak düşmanının zayıf noktasını bulup oraya vurursun." },
    { name: "Dread Ambusher", race: "General", class: "Ranger", type: "Pasif", dice: "+1 Saldırı", desc: "Savaşın ilk turunda aşırı hızlı hareket edip fazladan vurursun." },
    { name: "Beast Companion", race: "General", class: "Ranger", type: "Pasif", dice: "Hayvan Dostu", desc: "Yanında seninle birlikte savaşan sadık bir vahşi hayvanın vardır." },

    { name: "Shapechanger", race: "Changeling", class: "General", type: "Action", dice: "-", desc: "Görünüşünü ve sesini fiziksel olarak değiştirirsin. Boyun ve cinsiyetin dahil." },
    { name: "Changeling Instincts", race: "Changeling", class: "General", type: "Pasif", dice: "-", desc: "İkna, Aldatma veya Sezgi yeteneklerinden ikisinde otomatik uzmanlık kazanırsın." },
    { name: "Divergent Persona", race: "Changeling", class: "General", type: "Pasif", dice: "x2 Bonus", desc: "Bir görsel kimliğinle özdeşleşen bir araçta (Örn: Zar seti) uzmanlık bonusun iki katına çıkar." },
    { name: "Linguistic Intuition", race: "Changeling", class: "General", type: "Pasif", dice: "-", desc: "Duyduğun dillerin aksanlarını ve konuşma tarzlarını anında kavrayıp taklit edebilirsin." },
    { name: "Unsettling Presence", race: "Changeling", class: "General", type: "Reaction", dice: "Dezavantaj", desc: "Sana saldıran birine anlık korkutucu bir form göstererek saldırısını zorlaştırırsın." },
    { name: "Silver Tongue", race: "Changeling", class: "Bard", type: "Pasif", dice: "Min 10", desc: "İkna zarlarında 1-9 arasını 10 sayarsın. (College of Eloquence ile birleşince)." },
    { name: "Persona Weaver", race: "Changeling", class: "General", type: "Action", dice: "-", desc: "Kıyafetlerini illüzyonla değil, fiziksel olarak hızlıca değiştirebilme yeteneği." },
    { name: "Psychic Resistance", race: "Changeling", class: "General", type: "Pasif", dice: "Direnç", desc: "Zihnini okumaya çalışanlara karşı direnç kazanırsın." },
    { name: "Hidden Face", race: "Changeling", class: "General", type: "Pasif", dice: "Avantaj", desc: "Gerçek formunu gizleme zarlarında (Deception) avantajlısın." },
    { name: "Fluid Mind", race: "Changeling", class: "General", type: "Pasif", dice: "-", desc: "Zihinsel kontrol büyülerinden (Charm) kurtulma zarların daha yüksektir." },

    { name: "Darkvision", race: "Elf", class: "General", type: "Pasif", dice: "18 Metre", desc: "Karanlıkta sanki ışık varmış gibi net görebilirsin." },
    { name: "Fey Ancestry", race: "Elf", class: "General", type: "Pasif", dice: "-", desc: "Büyüyle uyutulamazsın ve büyülenmeye (Charm) karşı dirençlisin." },
    { name: "Trance", race: "Elf", class: "General", type: "Pasif", dice: "4 Saat", desc: "Uyumazsın, 4 saatlik meditasyon tam bir uyku yerine geçer." },
    { name: "Keen Senses", race: "Elf", class: "General", type: "Pasif", dice: "Algı +2", desc: "Algı (Perception) yeteneğinde doğuştan yeteneklisin." },
    { name: "Elf Weapon Training", race: "Elf", class: "General", type: "Pasif", dice: "-", desc: "Kılıç ve yay kullanımında profesyonel eğitimlisin." },
    { name: "High Elf Cantrip", race: "Elf", class: "General", type: "Action", dice: "Büyü", desc: "Bir adet büyücü (Wizard) büyüsünü doğuştan bilirsin." },
    { name: "Mask of the Wild", race: "Elf", class: "General", type: "Pasif", dice: "-", desc: "Hafif yağmur, sis veya bitki örtüsü arkasında saklanabilirsin." },
    { name: "Drow Magic", race: "Elf", class: "General", type: "Action", dice: "-", desc: "Dancing Lights ve Darkness gibi karanlık sanatları bilirsin." },
    { name: "Elven Accuracy", race: "Elf", class: "General", type: "Pasif", dice: "3 Zar", desc: "Avantajlı olduğun zarlarda 2 yerine 3 zar atıp en büyüğünü alırsın." },
    { name: "Fey Step", race: "Elf", class: "General", type: "Bonus Action", dice: "Işınlan", desc: "Kısa mesafeli ışınlanma yaparak zor durumlardan kaçarsın." },

    { name: "Dwarven Resilience", race: "Dwarf", class: "General", type: "Pasif", dice: "Direnç", desc: "Zehir hasarına karşı dirençlisin ve zehirlenme zarların avantajlı." },
    { name: "Stonecunning", race: "Dwarf", class: "General", type: "Pasif", dice: "x2 Uzmanlık", desc: "Taş yapılar hakkındaki tarih bilginde bonusun ikiye katlanır." },
    { name: "Dwarven Combat Training", race: "Dwarf", class: "General", type: "Pasif", dice: "-", desc: "Balta ve çekiç türü silahlarda doğuştan uzmanlık." },
    { name: "Tool Proficiency", race: "Dwarf", class: "General", type: "Pasif", dice: "-", desc: "Demirci, biracı veya taş yontucu araçlarında uzmanlık." },
    { name: "Dwarven Toughness", race: "Dwarf", class: "General", type: "Pasif", dice: "+1 HP", desc: "Her seviyede canın normalden 1 fazla artar (Hill Dwarf)." },
    { name: "Dwarven Armor Training", race: "Dwarf", class: "General", type: "Pasif", dice: "-", desc: "Hafif ve orta zırh giymeyi doğuştan bilirsin (Mountain Dwarf)." },
    { name: "Dwarven Fortitude", race: "Dwarf", class: "General", type: "Action", dice: "HD + CON", desc: "Savaşta savunma yaparken (Dodge) aynı zamanda canını yenileyebilirsin." },
    { name: "Grudge Bearer", race: "Dwarf", class: "General", type: "Pasif", dice: "+Hasar", desc: "Kadim düşmanlarına (Orklar, Goblinler vb.) karşı daha etkili saldırırsın." },
    { name: "Stout Resilience", race: "Dwarf", class: "General", type: "Pasif", dice: "Avantaj", desc: "Bedensel dayanıklılık (Constitution) zarlarında daha başarılısın." },
    { name: "Heavy Plate Master", race: "Dwarf", class: "General", type: "Pasif", dice: "-", desc: "Ağır zırh giydiğinde hızın asla düşmez." },

    { name: "Extra Language", race: "Human", class: "General", type: "Pasif", dice: "-", desc: "İnsanlar çok seyahat ettiği için fazladan bir dil bilirler." },
    { name: "Human Versatility", race: "Human", class: "General", type: "Pasif", dice: "+1 Tüm Statlar", desc: "Tüm temel yetenek puanların (Güç, Çeviklik vb.) 1 artar." },
    { name: "Variant Feat", race: "Human", class: "General", type: "Pasif", dice: "-", desc: "Oyuna başlarken fazladan 1 adet Hüner (Feat) seçme hakkı (Çok güçlüdür!)." },
    { name: "Skill Versatility", race: "Human", class: "General", type: "Pasif", dice: "-", desc: "İstediğin bir yetenekte (Örn: Gizlilik) uzmanlık kazanırsın." },
    { name: "Prodigy", race: "Human", class: "General", type: "Pasif", dice: "-", desc: "Bir yetenek, bir dil ve bir araçta ekstra uzmanlık kazanırsın." },
    { name: "Able Learner", race: "Human", class: "General", type: "Pasif", dice: "-", desc: "Yeni araçlar ve diller öğrenme süren yarı yarıya kısalır." },
    { name: "Determined Spirit", race: "Human", class: "General", type: "Pasif", dice: "Avantaj", desc: "Korkuya karşı direnç göstermekte daha başarılısın." },
    { name: "Human Ambition", race: "Human", class: "General", type: "Pasif", dice: "Zar Tekrarı", desc: "Günde bir kez başarısız olduğun bir yetenek zarını tekrar atabilirsin." },
    { name: "Social Adaptability", race: "Human", class: "General", type: "Pasif", dice: "İkna +2", desc: "Farklı kültürlere çok hızlı uyum sağlar ve insanları etkilersin." },
    { name: "Quick Thinking", race: "Human", class: "General", type: "Pasif", dice: "+İnisiyatif", desc: "Savaş başladığında herkesten önce hareket etme şansın yüksektir." },

    { name: "Breath Weapon", race: "Dragonborn", class: "General", type: "Action", dice: "2d6 Hasar", desc: "Ağzından ejderha türüne göre ateş, buz veya yıldırım püskürtürsün." },
    { name: "Draconic Ancestry", race: "Dragonborn", class: "General", type: "Pasif", dice: "-", desc: "Hangi ejderha soyundan geldiğini belirler (Kırmızı = Ateş vb.)." },
    { name: "Damage Resistance", race: "Dragonborn", class: "General", type: "Pasif", dice: "Yarı Hasar", desc: "Kendi elementine karşı dirençlisin (Ateş ejderiysen ateşten az hasar alırsın)." },
    { name: "Dragon Hide", race: "Dragonborn", class: "General", type: "Pasif", dice: "AC 13+DEX", desc: "Pulların zırh gibi sertleşir, zırhsızken bile korunursun." },
    { name: "Dragon Fear", race: "Dragonborn", class: "General", type: "Action", dice: "Wis Sav.", desc: "Nefes silahın yerine korkunç bir kükreme ile düşmanları kaçırırsın." },
    { name: "Draconic Wings", race: "Dragonborn", class: "General", type: "Pasif", dice: "Uçuş", desc: "Bazı soylarda sırtından kanatlar çıkar ve uçabilirsin." },
    { name: "Elemental Cleave", race: "Dragonborn", class: "General", type: "Pasif", dice: "+1d6 Hasar", desc: "Silah saldırılarına ejderha elementini eklersin." },
    { name: "Hardened Scales", race: "Dragonborn", class: "General", type: "Pasif", dice: "+1 AC", desc: "Pulların her türlü darbeye karşı daha dayanıklıdır." },
    { name: "Roar of Victory", race: "Dragonborn", class: "General", type: "Bonus Action", dice: "-", desc: "Bir düşman yendiğinde kükreyerek arkadaşlarına moral verirsin." },
    { name: "Ancient Lore", race: "Dragonborn", class: "General", type: "Pasif", dice: "Tarih +2", desc: "Ejderhalar ve antik tarih konusundaki bilgin çok derindir." },

    { name: "Hellish Resistance", race: "Tiefling", class: "General", type: "Pasif", dice: "Ateş Direnci", desc: "Cehennem kanın sayesinde ateşe karşı doğal direncin vardır." },
    { name: "Infernal Legacy", race: "Tiefling", class: "General", type: "Action", dice: "Büyü", desc: "Thaumaturgy, Hellish Rebuke ve Darkness büyülerini doğuştan bilirsin." },
    { name: "Winged Tiefling", race: "Tiefling", class: "General", type: "Pasif", dice: "Uçuş", desc: "Bazı Tieflinglerin yarasa benzeri kanatları vardır." },
    { name: "Devil's Tongue", race: "Tiefling", class: "General", type: "Action", dice: "Büyü", desc: "Vicious Mockery ve Charm Person büyülerini kullanarak insanları manipüle edersin." },
    { name: "Hellish Rebuke", race: "Tiefling", class: "General", type: "Reaction", dice: "2d10 Hasar", desc: "Sana vuran kişiyi anında cehennem ateşiyle yakarsın." },
    { name: "Flames of Phlegethos", race: "Tiefling", class: "General", type: "Pasif", dice: "Ateş Kalkanı", desc: "Ateş büyüsü yaptığında etrafında seni koruyan alevler çıkar." },
    { name: "Infernal Constitution", race: "Tiefling", class: "General", type: "Pasif", dice: "Direnç", desc: "Soğuk ve Zehir hasarına karşı da direnç kazanırsın." },
    { name: "Barbed Hide", race: "Tiefling", class: "General", type: "Pasif", dice: "1d4 Hasar", desc: "Sana sarılan veya dokunan düşmanlar derindeki dikenlerden hasar alır." },
    { name: "Eyes of the Abyss", race: "Tiefling", class: "General", type: "Pasif", dice: "Darkvision+", desc: "Büyülü karanlıkta bile görebilme yeteneği." },
    { name: "Cursed Touch", race: "Tiefling", class: "General", type: "Action", dice: "Dezavantaj", desc: "Dokunduğun birinin şansını bir turluğuna karartırsın." },

    { name: "Relentless Endurance", race: "Half-Orc", class: "General", type: "Pasif", dice: "1 HP Kalır", desc: "Canın 0'a düştüğünde ölmezsin, bir kez mahsus 1 HP ile ayakta kalırsın." },
    { name: "Savage Attacks", race: "Half-Orc", class: "General", type: "Pasif", dice: "Ekstra Zar", desc: "Kritik vurduğunda silah hasar zarını bir kez fazladan atarsın." },
    { name: "Menacing", race: "Half-Orc", class: "General", type: "Pasif", dice: "Intimidation", desc: "Göz korkutma yeteneğinde doğuştan uzmanlığın vardır." },
    { name: "Orcish Fury", race: "Half-Orc", class: "General", type: "Action", dice: "+1 Zar", desc: "Öfkeyle saldırıp bir saldırıya ekstra hasar zarı eklersin." },
    { name: "Adrenaline Rush", race: "Half-Orc", class: "General", type: "Bonus Action", dice: "Depar", desc: "Savaşta bir kez hızlıca yer değiştirmek için bedava depar atarsın." },
    { name: "Powerful Build", race: "Half-Orc", class: "General", type: "Pasif", dice: "2 Kat Taşıma", desc: "Taşıma kapasiten kendinden bir boy büyük yaratıklar gibidir." },
    { name: "Battle Cry", race: "Half-Orc", class: "General", type: "Action", dice: "Avantaj", desc: "Kükreyerek yanındaki arkadaşlarına bir sonraki saldırıda avantaj verirsin." },
    { name: "Thick Skin", race: "Half-Orc", class: "General", type: "Pasif", dice: "-1 Hasar", desc: "Gelen her fiziksel darbeden 1 hasar daha az alırsın." },
    { name: "Grit", race: "Half-Orc", class: "General", type: "Pasif", dice: "Avantaj", desc: "Sersemletmeye (Stun) karşı direnç zarların avantajlıdır." },
    { name: "Brute Force", race: "Half-Orc", class: "General", type: "Pasif", dice: "+Hasar", desc: "Eşyaları parçalarken veya kapı kırarken güç bonusun ikiye katlanır." },

    { name: "Lucky (Şanslı)", race: "Halfling", class: "General", type: "Pasif", dice: "Yeniden Atış", desc: "Zarda 1 atarsan o zarı geçersiz sayıp tekrar atabilirsin." },
    { name: "Brave (Cesur)", race: "Halfling", class: "General", type: "Pasif", dice: "Avantaj", desc: "Korkutulmaya karşı yapılan kurtarma zarlarında avantajlısın." },
    { name: "Halfling Nimbleness", race: "Halfling", class: "General", type: "Pasif", dice: "-", desc: "Senden büyük yaratıkların arasından (bacaklarının arasından vb.) geçebilirsin." },
    { name: "Naturally Stealthy", race: "Halfling", class: "General", type: "Pasif", dice: "-", desc: "Senden büyük bir canlının arkasına geçerek bile saklanabilirsin." },
    { name: "Stout Resilience", race: "Halfling", class: "General", type: "Pasif", dice: "Avantaj", desc: "Zehirlenmeye karşı dirençli ve dayanıklısın (Stout Halfling)." },
    { name: "Bountiful Luck", race: "Halfling", class: "General", type: "Reaction", dice: "Yeniden Atış", desc: "Yanındaki bir arkadaşın 1 atarsa, onun zarını tekrar attırırsın." },
    { name: "Second Chance", race: "Halfling", class: "General", type: "Reaction", dice: "Dezavantaj", desc: "Birisi sana vurduğunda şansını kullanıp ona zarı tekrar attırırsın." },
    { name: "Small But Mighty", race: "Halfling", class: "General", type: "Pasif", dice: "+Hasar", desc: "Senden çok büyük yaratıklara vurduğunda ekstra moral hasarı verirsin." },
    { name: "Lightfoot Stealth", race: "Halfling", class: "General", type: "Pasif", dice: "Avantaj", desc: "Hareket halindeyken gizlilik (Stealth) zarların daha yüksektir." },
    { name: "Hearth Spirit", race: "Halfling", class: "General", type: "Action", dice: "Can Ver", desc: "Bir arkadaşına yemek veya moral vererek küçük bir miktar can yenilersin." },

    { name: "Gnome Cunning", race: "Gnome", class: "General", type: "Pasif", dice: "Avantaj", desc: "Büyülere karşı yapılan tüm zekâ, bilgelik ve karizma zarlarında avantajlısın." },
    { name: "Artificer's Lore", race: "Gnome", class: "General", type: "Pasif", dice: "x2 Uzmanlık", desc: "Büyülü eşyalar ve teknolojik aletler hakkındaki bilginde bonusun katlanır." },
    { name: "Tinker (Mucit)", race: "Gnome", class: "General", type: "Action", dice: "-", desc: "Saatli bomba, ateş yakıcı veya müzik kutusu gibi küçük aletler yaparsın." },
    { name: "Speak with Small Beasts", race: "Gnome", class: "General", type: "Pasif", dice: "-", desc: "Tavşan, sincap, kuş gibi küçük hayvanlarla basit düzeyde konuşabilirsin." },
    { name: "Natural Illusionist", race: "Gnome", class: "General", type: "Action", dice: "Minor Illusion", desc: "Doğuştan Minor Illusion büyüsünü bilirsin." },
    { name: "Stone Camouflage", race: "Gnome", class: "General", type: "Pasif", dice: "Avantaj", desc: "Kayalık alanlarda saklanma zarların avantajlıdır." },
    { name: "Fade Away", race: "Gnome", class: "Reaction", type: "Action", dice: "Görünmezlik", desc: "Hasar aldığında anlık olarak görünmez olup kaçabilirsin." },
    { name: "Master Tinker", race: "Gnome", class: "General", type: "Pasif", dice: "-", desc: "Yaptığın icatları daha ucuza ve daha hızlı tamir edersin." },
    { name: "Magical Insight", race: "Gnome", class: "General", type: "Pasif", dice: "Analiz", desc: "Bir büyünün ne olduğunu anlamak için yapılan zarlarda uzmansın." },
    { name: "Escape Artist", race: "Gnome", class: "General", type: "Bonus Action", dice: "Avantaj", desc: "Bağlandığında veya yakalandığında kurtulma zarların avantajlıdır." },

    { name: "Celestial Resistance", race: "Aasimar", class: "General", type: "Pasif", dice: "Direnç", desc: "Işık (Radiant) ve Karanlık (Necrotic) hasarlarına karşı dirençlisin." },
    { name: "Healing Hands", race: "Aasimar", class: "General", type: "Action", dice: "Sev. kadar Can", desc: "Dokunarak birini seviyen kadar can puanı ile iyileştirirsin." },
    { name: "Light Bearer", race: "Aasimar", class: "General", type: "Action", dice: "Işık", desc: "İstediğin an etrafı aydınlatan kutsal bir ışık çıkarırsın." },
    { name: "Radiant Soul", race: "Aasimar", class: "General", type: "Action", dice: "Uçuş + Hasar", desc: "Sırtından ışık kanatları çıkar, uçarsın ve saldırıların ışık hasarı verir." },
    { name: "Necrotic Shroud", race: "Aasimar", class: "General", type: "Action", dice: "Korkutma", desc: "Etrafına karanlık bir aura yayarak düşmanları dehşete düşürürsün." },
    { name: "Radiant Consumption", race: "Aasimar", class: "General", type: "Action", dice: "Alan Hasarı", desc: "Vücudun o kadar parlar ki etrafındaki herkese ışık hasarı verirsin." },
    { name: "Angelic Guidance", race: "Aasimar", class: "General", type: "Pasif", dice: "Rehberlik", desc: "Zor bir kararda içindeki meleksi ses sana yol gösterir (Avantaj)." },
    { name: "Celestial Revelation", race: "Aasimar", class: "General", type: "Action", dice: "-", desc: "Gerçek formunu göstererek etrafındaki büyüleri bozabilirsin." },
    { name: "Devine Message", race: "Aasimar", class: "General", type: "Action", dice: "Telepati", desc: "Kutsal bir fısıltıyla uzaklardaki birine mesaj iletirsin." },
    { name: "Searing Light", race: "Aasimar", class: "General", type: "Action", dice: "Kör Etme", desc: "Gözlerinden çıkan parlak ışıkla bir düşmanı geçici olarak kör edersin." },

    { name: "Feline Agility", race: "Tabaxi", class: "General", type: "Pasif", dice: "2x Hız", desc: "Bir tur boyunca hızını iki katına çıkarabilirsin." },
    { name: "Cat's Claws", race: "Tabaxi", class: "General", type: "Action", dice: "1d4 Hasar", desc: "Keskin pençelerinle saldırabilir ve çok hızlı tırmanabilirsin." },
    { name: "Cat's Talent", race: "Tabaxi", class: "General", type: "Pasif", dice: "-", desc: "Gizlilik (Stealth) ve Algı (Perception) yeteneklerinde uzmansın." },
    { name: "Climber", race: "Tabaxi", class: "General", type: "Pasif", dice: "-", desc: "Düz duvarlara tırmanırken hızın azalmaz." },
    { name: "Hunter's Instinct", race: "Tabaxi", class: "General", type: "Pasif", dice: "Avantaj", desc: "Hareket eden bir hedefi takip ederken (Survival) avantajlısın." },
    { name: "Quick Reflexes", race: "Tabaxi", class: "General", type: "Pasif", dice: "+İnisiyatif", desc: "Kedi reflekslerin sayesinde savaşa her zaman hızlı girersin." },
    { name: "Soft Fall", race: "Tabaxi", class: "Reaction", dice: "- Hasar", desc: "Yüksekten düştüğünde aldığın hasarı pençelerin ve esnekliğinle azaltırsın." },
    { name: "Night Eye", race: "Tabaxi", class: "General", type: "Pasif", dice: "Darkvision", desc: "Karanlıkta bir kedi gibi mükemmel görürsün." },
    { name: "Curiosity", race: "Tabaxi", class: "General", type: "Pasif", dice: "Araştırma +2", desc: "Yeni şeyler keşfetme ve sırları bulma konusunda doğuştan yeteneklisin." },
    { name: "Hissing Menace", race: "Tabaxi", class: "Bonus Action", dice: "Korkutma", desc: "Tıslayarak düşmanın sana saldırmasını bir anlığına tereddüt ettirirsin." },

    { name: "Stone's Endurance", race: "Goliath", class: "General", type: "Reaction", dice: "1d12+CON", desc: "Hasar aldığında vücudunu sertleştirip hasarı büyük oranda azaltırsın." },
    { name: "Powerful Build", race: "Goliath", class: "General", type: "Pasif", dice: "2x Taşıma", desc: "Devler kadar ağır şeyleri kaldırabilir ve itebilirsin." },
    { name: "Mountain Born", race: "Goliath", class: "General", type: "Pasif", dice: "-", desc: "Yüksek rakımlara ve dondurucu soğuklara karşı doğal bağışıklığın var." },
    { name: "Natural Athlete", race: "Goliath", class: "General", type: "Pasif", dice: "Atletizm", desc: "Atletizm (Athletics) yeteneğinde doğuştan uzmansın." },
    { name: "Crushing Grip", race: "Goliath", class: "General", type: "Action", dice: "Avantaj", desc: "Birini yakaladığında (Grapple) senden kurtulması neredeyse imkansızdır." },
    { name: "Giant's Strike", race: "Goliath", class: "General", type: "Pasif", dice: "+1d4 Hasar", desc: "Silah saldırılarına devasa gücünü ekleyerek ekstra hasar verirsin." },
    { name: "Indomitable Might", race: "Goliath", class: "General", type: "Pasif", dice: "-", desc: "Güç zarlarında zarda çok düşük atsan bile minimum bir değerin altına düşmezsin." },
    { name: "Cold Resistance", race: "Goliath", class: "General", type: "Pasif", dice: "Direnç", desc: "Kar ve buz büyüleri sana çok az zarar verir." },
    { name: "Heir of the Peaks", race: "Goliath", class: "General", type: "Pasif", dice: "Denge", desc: "Dar yüzeylerde yürürken asla dengeni kaybetmezsin." },
    { name: "Steady Footing", race: "Goliath", class: "General", type: "Pasif", dice: "Yıkılmaz", desc: "Birinin seni yere devirmesi veya itmesi için gereken zorluk çok yüksektir." }
];